# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1381902730);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1381903007);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1381903127);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1381844404);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.slowStartup.averageTime", 9571);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20130911155657");
user_pref("browser.startup.homepage_override.mstone", "24.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1381930683119");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1381902954323");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1381903187858");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-info-bar-dismissed");
user_pref("datareporting.policy.firstRunTime", "1381844283119");
user_pref("datareporting.sessions.current.activeTicks", 153);
user_pref("datareporting.sessions.current.firstPaint", 9791);
user_pref("datareporting.sessions.current.main", 1362);
user_pref("datareporting.sessions.current.sessionRestored", 9460);
user_pref("datareporting.sessions.current.startTime", "1381902882710");
user_pref("datareporting.sessions.current.totalTime", 1497);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1381844279138,\"a\":22,\"t\":147246,\"c\":true,\"m\":1225,\"fp\":-1,\"sr\":9051}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1381902597932,\"a\":15,\"t\":97,\"c\":false,\"m\":1471,\"fp\":7370,\"sr\":16778}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"24.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\"},\"langpack-ru@firefox.mozilla.org\":{\"version\":\"24.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-ru@firefox.mozilla.org.xpi\"},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"24.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\"},\"webapps-team@lists.launchpad.net\":{\"version\":\"2.4.6\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2013.04.05.beta,online-accounts%40lists.launchpad.net:0.4.5,ubufox%40ubuntu.com:2.7,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.0");
user_pref("extensions.hotfix.certs.1.sha1Fingerprint", "91:53:98:0C:C1:86:DF:47:8F:35:22:9E:11:C9:A7:31:04:49:A1:AA");
user_pref("extensions.hotfix.lastVersion", "20130826.01");
user_pref("extensions.installCache", "[{\"name\":\"app-system-local\",\"addons\":{\"online-accounts@lists.launchpad.net\":{\"descriptor\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"mtime\":1366823102000,\"rdfTime\":1353000617000}}},{\"name\":\"app-system-share\",\"addons\":{\"webapps-team@lists.launchpad.net\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"mtime\":1366823102000,\"rdfTime\":1366057792000},\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1381846860000,\"rdfTime\":1375741654000},\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"mtime\":1366823102000,\"rdfTime\":1365165782000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1378918992000},\"langpack-ru@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-ru@firefox.mozilla.org.xpi\",\"mtime\":1378919074000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1378918992000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1381846683000,\"rdfTime\":1378917377000}}}]");
user_pref("extensions.lastAppVersion", "24.0");
user_pref("extensions.lastPlatformVersion", "24.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20130911155657");
user_pref("gecko.mstone", "24.0");
user_pref("idle.lastDailyNotification", 1381904553);
user_pref("intl.accept_languages", "ru,en-us,en");
user_pref("intl.charsetmenu.browser.cache", "windows-1251, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 34788);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1381902884);
user_pref("toolkit.telemetry.previousBuildID", "20130911155657");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1384436290);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
